#! /usr/bin/env python3

import sys
import os
import time

def Usage():
    print("!WARNING!:\n")
    print("USAGE:")
    print("\t ./make_gen ([flag] + [flag-content]) [project name]\n")
    print("!WARNING END!")

def Print_header(file):
    now = time.localtime(time.time())
    file.write("##\n")
    file.write("## Makefile for ")
    file.write(sys.argv[3])
    file.write(" in ")
    file.write(sys.path[0])
    file.write("\n")
    file.write("## \n")
    file.write("## Made by ")
    file.write(sys.argv[2])
    file.write("\n")
    file.write("## login   <")
    file.write(sys.argv[2])
    file.write("@epitech.net>\n")
    file.write("## \n")
    file.write("## Started on ")
    file.write(time.asctime(now))
    file.write(" ")
    file.write(sys.argv[2])
    file.write("\n")
    file.write("## Last update ")
    file.write(time.asctime(now))
    file.write(" ")
    file.write(sys.argv[2])
    file.write("\n")
    file.write("##\n\n")

def Print_Makefile_with_flags(file):
    file.write("CC\t=\t\n\n")
    file.write("NAME\t=\t")
    file.write(sys.argv[3])
    file.write("\n\n")
    file.write("CFLAGS\t+=\t\n\n")
    file.write("SRCS\t=\t\n\n")
    file.write("OBJS\t=\t$(SRCS:.c=.o)\n\n")
    file.write("RM\t=\trm -f\n\n")
    file.write("all: $(NAME)\n\n")
    file.write("$(NAME): $(OBJS)\n")
    file.write("\t$(CC) $(OBJS) -o $(NAME) $(CFLAGS)\n\n")
    file.write("clean:\n")
    file.write("\t$(RM) $(OBJS)\n\n")
    file.write("fclean: clean\n")
    file.write("\t$(RM) $(NAME)\n\n")
    file.write("re: fclean all\n\n")
    file.write(".phony: re fclean clean all")

def Print_Makefile(file):
    file.write("CC\t=\t\n\n")
    file.write("NAME\t=\t")
    file.write(sys.argv[1])
    file.write("\n\n")
    file.write("CFLAGS\t+=\t\n\n")
    file.write("SRCS\t=\t\n\n")
    file.write("OBJS\t=\t$(SRCS:.c=.o)\n\n")
    file.write("RM\t=\trm -f\n\n")
    file.write("all: $(NAME)\n\n")
    file.write("$(NAME): $(OBJS)\n")
    file.write("\t$(CC) $(OBJS) -o $(NAME) $(CFLAGS)\n\n")
    file.write("clean:\n")
    file.write("\t$(RM) $(OBJS)\n\n")
    file.write("fclean: clean\n")
    file.write("\t$(RM) $(NAME)\n\n")
    file.write("re: fclean all\n\n")
    file.write(".phony: re fclean clean all")

def Main():
    if len(sys.argv) == 1 or sys.argv[1] == "-h":
        Usage()
        return (0)
    else:
        try:
            os.remove("Makefile")
        except OSError:
            pass
        file = open("Makefile", "x")
        if sys.argv[1] == "-H":
            Print_header(file)
            Print_Makefile_with_flags(file)
        else:
            Print_Makefile(file)
        file.close()
        return (0)

Main()
